In [1]:
using MLDemos, DataFrames

INFO: Recompiling stale cache file /Users/abhijithc/.julia/lib/v0.4/LightXML.ji for module LightXML.
INFO: Recompiling stale cache file /Users/abhijithc/.julia/lib/v0.4/HttpParser.ji for module HttpParser.
INFO: Recompiling stale cache file /Users/abhijithc/.julia/lib/v0.4/Requests.ji for module Requests.
INFO: Recompiling stale cache file /Users/abhijithc/.julia/lib/v0.4/MbedTLS.ji for module MbedTLS.
INFO: Recompiling stale cache file /Users/abhijithc/.julia/lib/v0.4/Codecs.ji for module Codecs.


In [2]:
terms = readtable("$(Pkg.dir())/MLDemos/data/drug/data.csv", header=true)

254x3 DataFrames.DataFrame
| Row | |-----|
| 1   | | 2   | | 3   | | 4   | | 5   | | 6   | | 7   | | 8   | | 9   | | 10  | | 11  | 
⋮
| 243 | | 244 | | 245 | | 246 | | 247 | | 248 | | 249 | | 250 | | 251 | | 252 | | 253 | | 254 | 

| Row | Disease                                                                    |
|-----|----------------------------------------------------------------------------|
| 1   | "Epilepsy"                                                                 |
| 2   | "Glaucoma"                                                                 |
| 3   | "Arrhythmia"                                                               |
| 4   | "Calculus Urinary"                                                         |
| 5   | "Seizures"                                                                 |
| 6   | "Pruritis"                                                                 |
| 7   | "Cushings Syndrome"                                                        |
| 8   | "Deep Vein Thrombosis"                                                     |
| 9   | "Hypertension Ocular"                                                      |
| 10  | "Arterial Occlusion Peripheral"                                            |
| 11  | "Bipolar Affective Disorder"                                               |
⋮
| 243 | "Deficiency Vitamin"                                                       |
| 244 | "Fibrocystic Breast Disease"                                               |
| 245 | "Leprosy Lepromatous"                                                      |
| 246 | "Onchocerciasis |River blindness |Robles disease |African river blindness" |
| 247 | "Onchocerca volvulus | Onchocerca"                                         |
| 248 | "Wolbachia"                                                                |
| 249 | "filarial infection"                                                       |
| 250 | "microfilaria"                                                             |
| 251 | "microfilaricide"                                                          |
| 252 | "Nematodes"                                                                |
| 253 | NA                                                                         |
| 254 | NA                                                                         |

| Row | Drug                        |
|-----|-----------------------------|
| 1   | "Doxaprost"                 |
| 2   | "Doxazosin Mesylate"        |
| 3   | "Doxepin Hydrochloride"     |
| 4   | "Doxycycline Hydrochloride" |
| 5   | "Dracotanoside D"           |
| 6   | "Dragonamide B"             |
| 7   | "Dragonamide E"             |
| 8   | "Drobuline"                 |
| 9   | "Drospirenone"              |
| 10  | "Droxinavir Hydrochloride"  |
| 11  | "Drupanin"                  |
⋮
| 243 | "Droserone"                 |
| 244 | "Droxicam"                  |
| 245 | "Droxinavir"                |
| 246 | "Rapamycin"                 |
| 247 | "Sirolimus"                 |
| 248 | "Tacrolimus |fb506"         |
| 249 | "Clarithromycin"            |
| 250 | "Imatinib"                  |
| 251 | "Atorvastatin"              |
| 252 | "Bexarotene"                |
| 253 | NA                          |
| 254 | NA                          |

| Row | Target                                                                                          |
|-----|-------------------------------------------------------------------------------------------------|
| 1   | "Gonadotropin-Releasing Hormone Receptor"                                                       |
| 2   | "Metabotropic Glutamate Receptor 1"                                                             |
| 3   | "Metabotropic Glutamate Receptor 2"                                                             |
| 4   | "Metabotropic Glutamate Receptor 3"                                                             |
| 5   | "Pancreatic Alpha-Amylase"                 

In [3]:
drugs = dropna(terms[:Drug]);
targets = dropna(terms[:Target]);
diseases = dropna(terms[:Disease]);

In [43]:
size(drugs)

(252,)

In [44]:
all = [drugs[1:100];targets[1:100];diseases[1:100]]

300-element Array{UTF8String,1}:
 "Doxaprost"                 
 "Doxazosin Mesylate"        
 "Doxepin Hydrochloride"     
 "Doxycycline Hydrochloride" 
 "Dracotanoside D"           
 "Dragonamide B"             
 "Dragonamide E"             
 "Drobuline"                 
 "Drospirenone"              
 "Droxinavir Hydrochloride"  
 "Drupanin"                  
 "Kaad-Cyclopamine"          
 "Kabiramide K"              
 ⋮                           
 "Cardiac Dysrhythmia"       
 "Puberty Precocious"        
 "Aspergillosis"             
 "Meningitis Bacterial"      
 "Ankylosing Spondylitis"    
 "Pain Musculoskeletal"      
 "Hyperlipoproteinemia"      
 "Obstructive Airway Disease"
 "Iritis"                    
 "Carcinoma Endometrial"     
 "Anxiety Disorder"          
 "Somatoform Disorder"       

In [45]:
@time T = tdm(all, "PUBMED")

 Doxaprost [Title/Abstract] AND
 Doxazosin Mesylate [Title/Abstract] AND
 Doxepin Hydrochloride [Title/Abstract] AND
 Doxycycline Hydrochloride [Title/Abstract] AND
 Dracotanoside D [Title/Abstract] AND
 Dragonamide B [Title/Abstract] AND
 Dragonamide E [Title/Abstract] AND
 Drobuline [Title/Abstract] AND
 Drospirenone [Title/Abstract] AND
 Droxinavir Hydrochloride [Title/Abstract] AND
 Drupanin [Title/Abstract] AND
 Kaad-Cyclopamine [Title/Abstract] AND
 Kabiramide K [Title/Abstract] AND
 Kadcoccilactone A [Title/Abstract] AND
 Kadcoccilactone C [Title/Abstract] AND
 Kadcoccilactone D [Title/Abstract] AND
 Kadcoccilactone F [Title/Abstract] AND
 Kadsulactone A [Title/Abstract] AND
 Kadsuphilol C [Title/Abstract] AND
 Kadsuphilol E [Title/Abstract] AND
 Kadsuracoccinic Acid A [Title/Abstract] AND
 Kaempferitrin [Title/Abstract] AND
 Kaempferol [Title/Abstract] AND
 4-Medck Thiolactone [Title/Abstract] AND
 4-Mercaptopyridine [Title/Abstract] AND
 N-Heptanoyl-L-Homoserine Lactone [Title

300x27097379 sparse matrix with 2218 Int64 entries:
	[1       ,     7000]  =  1
	[268     ,   374316]  =  1
	[8       ,   692260]  =  1
	[245     ,   842879]  =  1
	[1       ,   935524]  =  1
	[212     ,  1055005]  =  1
	[298     ,  1152496]  =  1
	[245     ,  1152537]  =  1
	[290     ,  1276700]  =  1
	[198     ,  1332684]  =  1
	⋮
	[266     , 27097347]  =  1
	[5       , 27097348]  =  1
	[16      , 27097348]  =  1
	[111     , 27097354]  =  1
	[15      , 27097360]  =  1
	[15      , 27097363]  =  1
	[247     , 27097363]  =  1
	[96      , 27097368]  =  1
	[15      , 27097373]  =  1
	[281     , 27097379]  =  1
	[284     , 27097379]  =  1

In [47]:
@time tdmf=T .* log(size(T,2)./sum(T,2))

  0.369356 seconds (42 allocations: 206.779 MB, 5.86% gc time)


300x27097379 sparse matrix with 2218 Float64 entries:
	[1       ,     7000]  =  16.4218
	[268     ,   374316]  =  14.8124
	[8       ,   692260]  =  17.1149
	[245     ,   842879]  =  15.3232
	[1       ,   935524]  =  16.4218
	[212     ,  1055005]  =  16.0163
	[298     ,  1152496]  =  15.3232
	[245     ,  1152537]  =  15.3232
	[290     ,  1276700]  =  14.8124
	[198     ,  1332684]  =  15.3232
	⋮
	[266     , 27097347]  =  14.8124
	[5       , 27097348]  =  14.8124
	[16      , 27097348]  =  14.8124
	[111     , 27097354]  =  14.8124
	[15      , 27097360]  =  14.8124
	[15      , 27097363]  =  14.8124
	[247     , 27097363]  =  14.8124
	[96      , 27097368]  =  14.8124
	[15      , 27097373]  =  14.8124
	[281     , 27097379]  =  14.8124
	[284     , 27097379]  =  14.8124

In [48]:
@time dtmf=T' .* log(size(T',1)./sum(T',1))

  0.107908 seconds (61 allocations: 164.844 KB)


27097379x300 sparse matrix with 2218 Float64 entries:
	[7000    ,        1]  =  16.4218
	[935524  ,        1]  =  16.4218
	[22131637,        2]  =  14.8124
	[23385960,        2]  =  14.8124
	[23983168,        2]  =  14.8124
	[25007615,        2]  =  14.8124
	[25668796,        2]  =  14.8124
	[25840026,        2]  =  14.8124
	[26201344,        2]  =  14.8124
	[26328143,        2]  =  14.8124
	⋮
	[27096571,      299]  =  14.8124
	[26863248,      300]  =  14.8124
	[26919056,      300]  =  14.8124
	[26932754,      300]  =  14.8124
	[26944392,      300]  =  14.8124
	[26951025,      300]  =  14.8124
	[26984121,      300]  =  14.8124
	[26997020,      300]  =  14.8124
	[27037573,      300]  =  14.8124
	[27045631,      300]  =  14.8124
	[27064523,      300]  =  14.8124

In [49]:
function cosine_vectorized(i::SparseMatrixCSC{Float64, Int64}, j::SparseMatrixCSC{Float64, Int64})
    return sum(i .* j)/sqrt(sum(i.*i)*sum(j.*j))
end

cosine_vectorized (generic function with 1 method)

In [91]:
array(terms[1,:])[:]

3-element Array{UTF8String,1}:
 "Epilepsy"                               
 "Doxaprost"                              
 "Gonadotropin-Releasing Hormone Receptor"

In [92]:
dbsearch("PUBMED",array(terms[1,:])[:], "OR")

 Epilepsy [Title/Abstract] OR Doxaprost [Title/Abstract] OR Gonadotropin-Releasing Hormone Receptor [Title/Abstract] OR


MLDemos.PubIds(Nullable(UTF8String["Epilepsy","Doxaprost","Gonadotropin-Releasing Hormone Receptor"]),Nullable([27097007,27096812,27096250,27095821,27095588,27095555,27095099,27095080,27095079,27094525]),10)

In [104]:
d=dbsearch("PUBMED",[terms[1,2]], "OR")

 Doxaprost [Title/Abstract] OR


MLDemos.PubIds(Nullable(UTF8String["Doxaprost"]),Nullable([935524,7000]),2)

In [115]:
drug = get(d.pubids)

2-element Array{Int64,1}:
 935524
   7000

In [114]:
dis = get(di.pubids)

10-element Array{Int64,1}:
 27097007
 27096812
 27096250
 27095821
 27095588
 27095555
 27095099
 27095080
 27095079
 27094525

In [113]:
target=get(t.pubids)

10-element Array{Int64,1}:
 27063262
 27045358
 26953247
 26920257
 26892063
 26645560
 26580281
 26550267
 26373374
 26345908

In [63]:
@time D = zeros(r,r)
for i = 1:r
    for j = i+1:r
        D[i,j] = cosine_vectorized(tdmf[:,i],tdmf[:,j])
    end
end

  0.000692 seconds (9 allocations: 703.422 KB)


In [64]:
Ds = sparse(D)

300x300 sparse matrix with 44850 Float64 entries:
	[1  ,   2]  =  NaN
	[1  ,   3]  =  NaN
	[2  ,   3]  =  NaN
	[1  ,   4]  =  NaN
	[2  ,   4]  =  NaN
	[3  ,   4]  =  NaN
	[1  ,   5]  =  NaN
	[2  ,   5]  =  NaN
	[3  ,   5]  =  NaN
	[4  ,   5]  =  NaN
	⋮
	[289, 300]  =  NaN
	[290, 300]  =  NaN
	[291, 300]  =  NaN
	[292, 300]  =  NaN
	[293, 300]  =  NaN
	[294, 300]  =  NaN
	[295, 300]  =  NaN
	[296, 300]  =  NaN
	[297, 300]  =  NaN
	[298, 300]  =  NaN
	[299, 300]  =  NaN

In [62]:
Ds.nzval


9670-element Array{Float64,1}:
   1.0
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
   ⋮  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
 NaN  
   0.1

In [34]:
dtmf[:,2]

27097348x1 sparse matrix with 10 Float64 entries:
	[22131637,        1]  =  14.8124
	[23385960,        1]  =  14.8124
	[23983168,        1]  =  14.8124
	[25007615,        1]  =  14.8124
	[25668796,        1]  =  14.8124
	[25840026,        1]  =  14.8124
	[26201344,        1]  =  14.8124
	[26328143,        1]  =  14.8124
	[26716887,        1]  =  14.8124
	[26735908,        1]  =  14.8124

In [35]:
all[11]

"Gonadotropin-Releasing Hormone Receptor"

In [36]:
all[1]

"Doxaprost"

In [37]:
all[21]

"Epilepsy"

In [39]:
dtmf[:,11]

27097348x1 sparse matrix with 10 Float64 entries:
	[26345908,        1]  =  14.8124
	[26373374,        1]  =  14.8124
	[26550267,        1]  =  14.8124
	[26580281,        1]  =  14.8124
	[26645560,        1]  =  14.8124
	[26892063,        1]  =  14.8124
	[26920257,        1]  =  14.8124
	[26953247,        1]  =  14.8124
	[27045358,        1]  =  14.8124
	[27063262,        1]  =  14.8124

In [40]:
dtmf[:,1]

27097348x1 sparse matrix with 2 Float64 entries:
	[7000    ,        1]  =  16.4218
	[935524  ,        1]  =  16.4218

In [42]:
dbsearch("PUBMED", [all[11]], "AND")

 Gonadotropin-Releasing Hormone Receptor [Title/Abstract] AND


MLDemos.PubIds(Nullable(UTF8String["Gonadotropin-Releasing Hormone Receptor"]),Nullable([27063262,27045358,26953247,26920257,26892063,26645560,26580281,26550267,26373374,26345908]),10)